{
 "title": "JFR",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "GC New Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_gc_seconds_bucket{collector=\"G1New\"}",
     "legendFormat": "New"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(rate(os_network_data_read_bytes_total[5m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(os_network_data_write_bytes_total[5m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "JVM Safepoint Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_safepoint_time_seconds_bucket"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "jvm_threads_total", "legendFormat": "total" },
    { "expr": "jvm_threads_daemon", "legendFormat": "deamon" },
    { "expr": "jvm_threads_peak", "legendFormat": "peak" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "os_cpu_usage{mode=\"combined\"} * 100",
     "legendFormat": "total"
    },
    {
     "expr": "os_cpu_usage{mode=\"user\"} * 100",
     "legendFormat": "user"
    },
    {
     "expr": "os_cpu_usage{mode=\"system\"} * 100",
     "legendFormat": "system"
    }
   ]
  }
 ]
}