# Provide datasources https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090/
    isDefault:
    version: 1
    editable: true
